finance/urls.py
from django.urls import path
from . views import *

app_name = 'finance'

urlpatterns = [
    path('', finance, name='finance'),
    path('pl_overview/', pl_overview, name='pl_overview'),
    path('income_json/', income_json, name='income_json'),
    path('expense_json/', expense_json, name='expense_json'),
    path('income_graph/', income_graph, name='income_graph'),
    path('expense_graph/', expense_graph, name='expense_graph'),
    
    # expenses 
    path('expenses', expenses, name='expenses'),
    path('get_expense/<int:expense_id>/',get_expense, name='get_expense'),
    path('add/expense/', add_expense_category, name='add_expense_category'),
    path('edit/expense/', add_or_edit_expense, name='add_or_edit_expense'),
    path('delete_expense/<int:expense_id>/', delete_expense, name='delete_expense'),
    path('update_expense_status/', update_expense_status, name='update_expense_status'),
    
    # cashbook 
    path('cashbook/', cashbook, name='cashbook'),
    path('cashbook/note/', cashbook_note, name='cashbook_note'),
    path('report/', download_cashbook_report, name='download_cashbook_report'),
    path('cancel-entry/', cancel_transaction, name='cancel-entry'),
    path('cashbook/note/<int:entry_id>/', cashbook_note_view, name='cashbook_note_view'),
    path('update_transaction_status/<int:pk>/', update_transaction_status, name='update_transaction_status'),
    
    # cogs
    path('cogs/', cogs_list, name='cogs'),
    
    # cashiers
    path('cashiers/', cashiers_list, name='cashiers_list'),
    
    # reports
    path('generate-report/', generate_report, name='generate_report'),
    
    # cash-ups
    path('cash_up/', cash_up, name='cash_up'),
    path('claim-cashup/<int:cashup_id>/', claim_cashup_difference, name='claim-cashup'),
    path('charge_cashup_difference/', charge_cashup_difference, name='charge_cashup_difference'),
    
    path('days_data', days_data, name='days_data'),

    #transaction logs
    path('transaction-logs', transaction_logs, name='logs'),

    #cashier expenses
    path('cashier-expenses/<int:cashier_id>/', cashier_expenses, name='cashier_expenses'),
]

pos/urls.py
from django.urls import path
from . views import *

app_name = 'pos'

urlpatterns = [
    path('', pos, name='pos' ),
    path('process/sale/', process_sale, name='process_sale'),
    path('sales/list', sales_list, name='sales_list'),
    # path('download-receipt/', generate_receipt_pdf, name='download_receipt'),
    path('product_meal_json/', product_meal_json, name='product_meal_json'),
    path('meal/detail/json/<int:meal_id>/', meal_detail_json, name='meal_detail_json'),
    
    path('change_list/', change_list, name='change_list'),
    path('create_change/', create_change, name='create_change'),
    path('report/', download_change_report, name='download_cashbook_report'),
    path('collect_change/', collect_change, name='collect_change'),

    # sales
    path('sales/<int:user_id>/', void_sales, name='sales'),

    #authenticate
    path('void/authenticate/', void_authenticate, name='void_authenticate'),

    # cash up
    path('cash_up/<int:cashier_id>/', cash_up, name='cash_up')
]

restaurant/urls.py
from .views import Dashboard
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path('pos/', include('pos.urls', namespace='pos')),
    path('', Dashboard, name='dashborad'),
    path("admin/", admin.site.urls),
    path('settings/', include('settings.urls', namespace='settings')),
    path('users/', include('users.urls', namespace='users')),
    path('analytics/', include('analytics.urls')),
    path('finance/', include('finance.urls', namespace='finance')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

finance/models.py
from django.db import models
from inventory.models import Meal, Product, Dish
from django.contrib.auth import get_user_model

User = get_user_model()

class ExpenseCategory(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self) -> str:
        return self.name

class COGS(models.Model):
    date = models.DateField(auto_now_add=True)
    production = models.ForeignKey('inventory.production', on_delete=models.CASCADE, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    
class Expense(models.Model):
    category = models.ForeignKey(ExpenseCategory, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=255)
    cancel = models.BooleanField(default=False)
    status = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return f'{self.amount}'

class Sale(models.Model):
    cashier = models.ForeignKey(User, on_delete=models.CASCADE)
    total_amount= models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    tax = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    sub_total = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    date = models.DateField(auto_now_add=True)
    receipt_number = models.CharField(max_length=10, blank=True)
    staff = models.BooleanField(default=False)
    change = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    void = models.BooleanField(default=False)

    
    def __str__(self) -> str:
        return f'{self.cashier} -> ({self.total_amount})'
    
    def save(self, *args, **kwargs):
        if not self.receipt_number:
            last_receipt = Sale.objects.all().order_by('id').last()
            if last_receipt:
                last_receipt_number = int(last_receipt.receipt_number)
                new_receipt_number = '{:04d}'.format(last_receipt_number + 1)
            else:
                new_receipt_number = '0001'
            self.receipt_number = new_receipt_number
        super(Sale, self).save(*args, **kwargs)
    
class SaleItem(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    time = models.TimeField(auto_now_add=True)
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE, null=True)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    
class CashBook(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, null=True)
    expense = models.ForeignKey(Expense, on_delete=models.CASCADE, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    debit = models.BooleanField(default=False, null=True)
    credit = models.BooleanField(default=False, null=True)
    description = models.CharField(max_length=255, default='')
    date = models.DateField(auto_now_add=True)
    manager = models.BooleanField(default=False)
    accountant = models.BooleanField(default=False, null=True)
    director = models.BooleanField(default=False, null=True)
    note = models.TextField(default='', null=True)
    cancelled = models.BooleanField(default=False, null=True)
    
    def __str__(self) -> str:
        return f'{self.amount}'
    
class CashBookNote(models.Model):
    entry = models.ForeignKey(CashBook, related_name="notes", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    note = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Note by {self.user.username} on {self.timestamp}"
    
class transactionLog(models.Model):
    action_choice = [
        ('sale', 'sale'),
        ('expense', 'expense'),
        
    ]
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, null=True)
    expense = models.ForeignKey(Expense, on_delete=models.CASCADE, null=True)
    action = models.CharField(max_length=10, choices=action_choice)
    
    
class CashUp(models.Model):
    cashier = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cashier')
    cashed_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    sales = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return f'{self.date}'
    
class CashierAccount(models.Model):
    cashier = models.ForeignKey(User, on_delete=models.CASCADE)
    cash_up = models.ForeignKey(CashUp, on_delete=models.CASCADE, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    status = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return f'{self.cashier.first_name} ({self.amount})'

class CashierPayments(models.Model):
    date = models.DateTimeField(auto_now_add=True, null=True)
    cashier = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    
    def __str__(self) -> str:
        return f'{self.cashier.cashier.first_name} ({self.amount})'
     
class EmailNotifications(models.Model):
    expense_notification = models.BooleanField(default=True)
    
class Change(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, related_name='sale_change')
    name = models.CharField(max_length=100)
    phonenumber = models.CharField(max_length=20)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    receipt_number = models.CharField(max_length=100)
    collected = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    cashier = models.ForeignKey(User, on_delete=models.CASCADE)
    claimed = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return f'{self.cashier.username} ({self.amount})'
    
class CashierExpense(models.Model):
    name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    cashier = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    description = models.CharField(max_length=255)
    status = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.name} ({self.amount})'

finance/forms.py
from django import forms
from . models import *

class ExpensesForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['category', 'amount', 'description']
        
class ExpenseCategoryForm(forms.ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ['name']

class CashUpForm(forms.ModelForm):
    class Meta:
        model = CashUp
        fields = ['cashier', 'cashed_amount']
        
class ChangeForm(forms.ModelForm):
    class Meta:
        model : Change
        exclude = ['cacshier', 'collected', 'claimed']

class CashierExpenseForm(forms.ModelForm):
    class Meta:
        model = CashierExpense
        exclude = ['cashier', 'date']

templates/finance/cashups.html
{% extends "base.html" %}
{% load static %}
{% block title %}Cash Ups{% endblock title %}
{% block content %}
<div>
    <nav class="d-flex justify-content-between align-items-center rounded mb-2 py-2 border-bottom">
        <div>
            <a href='{% url "finance:finance"%}' class='border btn bx bx-arrow-back fs-5'></a>
            <a href='/' class='bx bx-home btn border fs-5 mx-2'></a>
            <span class='mt-2 fs-5'>Cash Ups</span>
        </div>
        <div class="d-flex justify-content-between mt-1">
            <div>
                <select class="form-select" id="filterSelect" onchange="filterCashBook()">
                    <option value="today" {% if filter_option == 'today' %}selected{% endif %}>Today</option>
                    <option value="this_week" {% if filter_option == 'this_week' %}selected{% endif %}>This Week</option>
                    <option value="yesterday" {% if filter_option == 'yesterday' %}selected{% endif %}>Yesterday</option>
                    <option value="this_month" {% if filter_option == 'this_month' %}selected{% endif %}>This Month</option>
                    <option value="last_month" {% if filter_option == 'last_month' %}selected{% endif %}>Last Month</option>
                    <option value="this_year" {% if filter_option == 'this_year' %}selected{% endif %}>This Year</option>
                </select>
            </div>
            <div id="customDateRange" class="d-flex mx-2">
                <input type="date" id="startDate" value="{{ start_date }}" class="form-control" placeholder="Start Date">
                <input type="date" id="endDate" value="{{ end_date}}" class="form-control mx-2" placeholder="End Date">
                <button class="btn btn-primary" onclick="applyCustomFilter()">Apply</button>
            </div>
            <button class="btn btn-secondary" onclick="downloadReport()">Download Report</button>
        </div>
    </nav>
    <table class="table table-hover table-striped table-bordered" id="cash_up_table">
        <thead>
            <th>date</th>
            <th>Cashier</th>
            <th>Done By</th>
            <th>Sales</th>
            <th>Cashed Amount</th>
            <th>Status</th>
            <!-- <th>Action</th> -->
        </thead>
        <tbody>
            {% for cashup in cashups %}
                <tr data-cashup-id="{{ cashup.id }}">
                    <td><small>{{ cashup.date }}</small></td>
                    <td><small>{{ cashup.cashier }}</small></td>
                    <td><small>{{ cashup.user }}</small></td>
                    <td><small class="sales">{{ cashup.sales }}</small></td>
                    <td><small class="cashed-amount">{{ cashup.cashed_amount}}</small></td>
                    <td>
                        <small class="status">
                            {% if cashup.status %}
                                Done
                            {% else %}
                                {% if cashup.cashed_amount > cashup.sales %}
                                    <a href="" class="btn btn-outline-dark claim-amount w-100">claim</a>
                                {% else %}
                                    <a href="" class="btn btn-outline-dark charge-cashier w-100">charge cashier</a>
                                {% endif %}
                            {% endif %}
                        </small>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="modal fade" id="cashUpModal" tabindex="-1" aria-labelledby="cashUpModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="cashUpModalLabel">Create Cash Up</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="cashUpForm">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="cashier" class="form-label">Cashier</label>
                            <select id="cashier" class="form-select" required>
                                {% for user in cashier_list %}
                                    <option value="{{ user.id }}">{{ user.username }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="cashed_amount" class="form-label">Cashed Amount</label>
                            <input type="number" class="form-control" id="cashed_amount" required>
                        </div>
                        <div class="d-flex justify-content-end">
                            <button type="reset" class="btn btn-danger mx-2 bx bx-reset"></button>
                            <button type="button" class="btn btn-primary bx bx-save" onclick="submitCashUp()"></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    new DataTable('#cash_up_table')

    function filterCashBook() {
        const filter = document.getElementById('filterSelect').value;
        window.location.href = `?filter=${filter}`;
    }

    function applyCustomFilter() {
        const startDate = document.getElementById('startDate').value;
        const endDate = document.getElementById('endDate').value;
        if (startDate && endDate) {
            window.location.href = `?filter=custom&start_date=${startDate}&end_date=${endDate}`;
        } else {
            Swal.fire({
                title: "Error",
                text: "Please select both start and end dates.",
                icon: "error"
            });
        }
    }

    function downloadReport() {
        const filter = document.getElementById('filterSelect').value;
        let url = `?filter=${filter}&download=${true}/`;

        if (filter === 'custom') {
            const startDate = document.getElementById('startDate').value;
            const endDate = document.getElementById('endDate').value;
            url += `&start_date=${startDate}&end_date=${endDate}`;
        }

        window.location.href = url;
    }


    const rows = document.querySelectorAll("#cash_up_table tbody tr");

        rows.forEach(row => {
            const sales = parseFloat(row.querySelector(".sales").textContent.trim());
            const cashedAmount = parseFloat(row.querySelector(".cashed-amount").textContent.trim());
            const cashupId = row.getAttribute('data-cashup-id');

            const difference = (cashedAmount - sales).toFixed(2);

            const claimButton = row.querySelector(".claim-amount");
            const chargeButton = row.querySelector(".charge-cashier");

            if (cashedAmount > sales && claimButton) {
                claimButton.textContent = `claim ($${difference})`;
                claimButton.addEventListener('click', function(event) {
                    event.preventDefault();
                    claimCashupDifference(cashupId, difference);
                });
            } else if (sales > cashedAmount && chargeButton) {
                const chargeAmount = (sales - cashedAmount).toFixed(2)
                
                chargeButton.textContent = `charge cashier ($${chargeAmount})`;
                chargeButton.addEventListener('click', function(event) {
                    event.preventDefault();
                    chargeCashupDifference(cashupId, chargeAmount);
                });
            }
        });

    function claimCashupDifference(cashupId, claimAmount) {
        fetch(`/finance/claim-cashup/${cashupId}/`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}',
            },
            body: JSON.stringify({
                cashup_id: cashupId,
                claim_amount: claimAmount
            }),
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                Swal.fire({
                    title: 'Success!',
                    text: data.message,
                    icon: 'success',
                    confirmButtonText: 'OK'
                }).then(() => {
                    window.location.reload();
                });
            } else {
                Swal.fire({
                    title: 'Error!',
                    text: data.message,
                    icon: 'error',
                    confirmButtonText: 'OK'
                });
            }
        })
        .catch(error => {
            console.error('Error:', error);
            Swal.fire({
                title: 'Error!',
                text: 'Something went wrong!',
                icon: 'error',
                confirmButtonText: 'OK'
            });
        });
    }

    function chargeCashupDifference(cashupId, chargeAmount) {
        fetch(`/finance/charge_cashup_difference/`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}',
            },
            body: JSON.stringify({
                cashup_id: cashupId,
                charge_amount: chargeAmount
            }),
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                Swal.fire({
                    title: 'Success!',
                    text: data.message,
                    icon: 'success',
                    confirmButtonText: 'OK'
                }).then(() => {
                    window.location.reload();
                });
            } else {
                Swal.fire({
                    title: 'Error!',
                    text: data.message,
                    icon: 'error',
                    confirmButtonText: 'OK'
                });
            }
        })
        .catch(error => {
            console.error('Error:', error);
            Swal.fire({
                title: 'Error!',
                text: 'Something went wrong!',
                icon: 'error',
                confirmButtonText: 'OK'
            });
        });
    }


    function submitCashUp() {
        const cashier = document.getElementById('cashier').value;
        const cashed_amount = document.getElementById('cashed_amount').value;

        fetch("{% url 'finance:cash_up' %}", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": "{{ csrf_token }}"
            },
            body: JSON.stringify({
                cashier: cashier,
                cashed_amount: cashed_amount
            })
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                Swal.fire({
                    icon: 'success',
                    title: 'Success!',
                    text: data.message,
                }).then(() => {
                    location.reload(); 
                });
            } else {
                Swal.fire({
                    icon: 'error',
                    title: 'Error!',
                    text: data.message,
                });
            }
        })
        .catch(error => {
            Swal.fire({
                icon: 'error',
                title: 'Error!',
                text: 'Something went wrong!',
            });
        });
    }
</script>
{% endblock content %}

templates/finance/change_list.html
{% extends "base.html" %}
{% load static%}
{% load crispy_forms_tags %}
{% block title%} Change list {% endblock%}
{% block content %}
<div class="Finance">
    <nav class="d-flex justify-content-between align-items-center rounded mb-3 py-3 border-bottom">
        <div>
            <a href='{% url "pos:pos"%}' class='border btn bx bx-arrow-back fs-5'></a>
            <span class='mt-2 fs-5 mx-2'>Change list</span>
        </div>
        <div>
            <div class="d-flex justify-content-between mt-1">
                <div>
                    <select class="form-select" id="filterSelect" onchange="filterCashBook()">
                        <option value="today" {% if filter_option == 'today' %}selected{% endif %}>Today</option>
                        <option value="this_week" {% if filter_option == 'this_week' %}selected{% endif %}>This Week</option>
                        <option value="yesterday" {% if filter_option == 'yesterday' %}selected{% endif %}>Yesterday</option>
                        <option value="this_month" {% if filter_option == 'this_month' %}selected{% endif %}>This Month</option>
                        <option value="last_month" {% if filter_option == 'last_month' %}selected{% endif %}>Last Month</option>
                        <option value="this_year" {% if filter_option == 'this_year' %}selected{% endif %}>This Year</option>
                    </select>
                </div>
                <div id="customDateRange" class="d-flex mx-2">
                    <input type="date" id="startDate" value="{{ start_date }}" class="form-control" placeholder="Start Date">
                    <input type="date" id="endDate" value="{{ end_date}}" class="form-control mx-2" placeholder="End Date">
                    <button class="btn btn-primary" onclick="applyCustomFilter()">Apply</button>
                </div>
                <button class="btn btn-secondary" onclick="downloadReport()">Download Report</button>
            </div>
        </div>
    </nav>
    <h2 class='py-2 mb-2'>Total amount of change: {{ total }}</h2>
    <div class='mt-3'>
        <table class="table table-hover table=-stripped" id="change_table" style="width: 100%;">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Name</th>
                    <th>Phone number</th>
                    <th>Amount</th>
                    <th>Receipt Number</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for change in changes %}
                  <tr>
                        <td><small>{{ change.timestamp }}</small></td>
                        <td><small>{{ change.name }}</small></td>
                        <td><small>{{ change.phonenumber}}</small></td>
                        <td><small>{{ change.amount }}</small></td>
                        <td><small>{{ change.receipt_number }}</small></td>
                        <td>
                            {% if change.collected %}
                                <small>
                                     Collected
                                </small>
                                {% else %}
                                    <button onclick='displayAmount({{ change.id }})' class='btn btn-outline-dark btn-sm w-100'>collect</button>
                            {% endif %}
                        </td>
                  </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="modal fade" id="amountModal" tabindex="-1" aria-labelledby="chargeModalLabel" aria-hidden="true">
            <div class="modal-dialog bg modal-dialog-centered">
                <div class="modal-content p-5">
                    <h5 class="fw-bold">Enter amount collected</h5>
                    <div>
                        <input type="number" id="id_amount" placeholder="Enter amount" class="form-control">
                    </div>
                    <div class="d-flex justify-content-end mt-2">
                        <button class="btn btn-danger btn-sm mx-2" data-bs-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary btn-sm" onclick="collectChange()">Collect</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
    
   <script>
        new DataTable('#change_table')

        let changeId = null;

        const displayAmount = (id) => {
            $('#amountModal').modal('show');
            changeId = id;
        }

        function filterCashBook() {
            const filter = document.getElementById('filterSelect').value;
            window.location.href = `?filter=${filter}`;
        }
        

        function applyCustomFilter() {
            const startDate = document.getElementById('startDate').value;
            const endDate = document.getElementById('endDate').value;
            if (startDate && endDate) {
                window.location.href = `?filter=custom&start_date=${startDate}&end_date=${endDate}`;
            } else {
                Swal.fire({
                    title: "Error",
                    text: "Please select both start and end dates.",
                    icon: "error"
                });
            }
        }
    
        function downloadReport() {
            const filter = document.getElementById('filterSelect').value;
            let url = `/pos/report/?filter=${filter}/`;
    
            if (filter === 'custom') {
                const startDate = document.getElementById('startDate').value;
                const endDate = document.getElementById('endDate').value;
                url += `&start_date=${startDate}&end_date=${endDate}`;
            }
    
            window.location.href = url;
        }

        function collectChange() {
            const data = {
                change_id: changeId,
                amount:parseFloat(document.getElementById('id_amount').value)
            };

            console.log(data)
        
            fetch('/pos/collect_change/', { 
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': getCSRFToken() 
                },
                body: JSON.stringify(data)
            })
            .then(response => response.json().then(data => ({
                status: response.status,
                data: data
            })))
            .then(res => {
                if (res.status === 200) {
                    Swal.fire({
                        icon: 'success',
                        title: 'Success!',
                        text: 'Change has been collected successfully.',
                        confirmButtonText: 'OK'
                    }).then(() => {
                        location.reload(); 
                    });
                } else {
                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: res.data.message,
                        confirmButtonText: 'OK'
                    });
                }
            })
            .catch(error => {
                Swal.fire({
                    icon: 'error',
                    title: 'Request Failed',
                    text: error.toString(),
                    confirmButtonText: 'OK'
                });
            });
        }
        
        function getCSRFToken() {
            const name = 'csrftoken';
            const cookieValue = document.cookie.split('; ').find(row => row.startsWith(name + '='));
            return cookieValue ? decodeURIComponent(cookieValue.split('=')[1]) : null;
        }
        
   </script>    
</div>
{% endblock %}