inventory/urls.py
from django.urls import path
from .views import *


app_name = 'inventory'

urlpatterns = [
    path('products/', products, name='products'),
    path('create/product/', product, name='product'),
    path('edit/product/<int:product_id>/', edit_inventory, name='edit_inventory'),
    path('product/detail/<int:product_id>/', product_detail, name='product_detail'),
    path('add/product/category/', add_product_category, name='add_product_category'),
    path('raw_material_json/', raw_material_json, name='raw_material_json'),

    path('inventory/', inventory, name='inventory_list'),
    
    # unit of measurement 
    path('unit_of_measurement/', unit_of_measurement, name='unit_of_measurement'),
    
    # production plan 
    path('production/plan/list', production_plans, name='production_plans'),
    path('confirm_declaration/', confirm_declaration, name='confirm_declaration'),
    path('create/production/plan', create_production_plan, name='create_production_plan'),
    path('yesterdays/left/overs/', yeseterdays_left_overs, name='yeseterdays_left_overs'),
    path('declared/production/plan/', yeseterdays_left_overs, name='declared_production_plan'),
    path('update_production_plan/<int:pp_id>/', update_production_plan, name='update_production_plan'),
    path('production_plan/detail/<int:pp_id>/', production_plan_detail, name='production_plan_detail'),
    path('confirm/production_plan/<int:pp_id>/', confirm_production_plan, name='confirm_production_plan'),
    path('declare/production_plan/<int:pp_id>/', declare_production_plan, name='declare_production_plan'),
    path('process/production_plan/<int:pp_id>/', process_production_plan_confirmation, name='process_production_plan'),
    path('process/minor_raw_materials/<int:pp_id>/', process_raw_materials, name='process_minor_raw_materials'),
    path('minor_raw_materials/<int:pp_id>/', minor_raw_materials, name='minor_raw_materials'),
    path('confirm/minor_raw_materials/<int:pp_id>/', confirm_minor_raw_materials, name='confirm_minor_raw_materials'),
    path('confirm/minor_raw_materials/', confirm_minor_raw, name='confirm_minor_raw'),
    path('production_raw_materials/', production_raw_materials, name='production_raw_materials'),
    path('production_rm/detail/<int:rm_id>/', production_rm_detail, name='production_rm_detail'),
    
    # supplier
    path('suppliers/list', suppliers, name='suppliers'),
    path('edit/supplier/', edit_supplier, name='edit_supplier'),
    path('create/supplier/', create_supplier, name='create_supplier'),
    path('supplier/json/list/', supplier_list_json, name='supplier_list_json'),
    path('supplier_prices/<str:raw_material_name>/', supplier_prices, name='supplier_prices'),

    #to remove
    path('home', p_home, name='p_home'),
    
    # ppurchase orders
    path('purchase_orders/list/', purchase_orders, name='purchase_orders'),
    path('print/purchase_order/<int:order_id>/', print_purchase_order, name='print_purchase_order'),
    path('purchase_order/create/', create_purchase_order, name='create_purchase_order'),
    path('purchase_order/receive/<int:order_id>/', receive_order, name='receive_order'),
    path('process/purchase_order/', process_received_order, name='process_received_order'),
    path('purchase_order/detail/<int:order_id>/', purchase_order_detail, name='purchase_order_detail'),
    path('purchase_order/delete/<int:purchase_order_id>/', delete_purchase_order, name='delete_purchase_order'),
    path('purchase_orders/status/<int:order_id>/', change_purchase_order_status, name='change_purchase_order_status'),
    
    # dishes
    path('dishes/', DishListView.as_view(), name='dish_list'),
    path('edit_dish/<int:dish_id>/', edit_dish, name='edit_dish'),
    path('create/dish/', add_dish, name='dish_create'),
    path('dishes/<int:pk>/edit/', DishUpdateView.as_view(), name='dish_update'),
    path('dishes/<int:pk>/delete/', DishDeleteView.as_view(), name='dish_delete'),
    path('dish_json_detail/', dish_json_detail, name='dish_json_detail'),
    path('dish_data_json/<int:dish_id>/', get_dish_data, name='dish_json'),
    
    # ingridients
    path('ingredients/', IngredientListView.as_view(), name='ingredient_list'),
    path('ingredients/<int:pk>/edit/', IngredientUpdateView.as_view(), name='ingredient_update'),
    path('ingredients/<int:pk>/delete/', IngredientDeleteView.as_view(), name='ingredient_delete'),
    
    # meals
    path('add/meal/', add_meal, name='add_meal'),
    path('meal/list', meal_list, name='meal_list'),
    path('meals/<int:meal_id>/edit/', edit_meal, name='edit_meal'),
    path('meals/delete/<int:meal_id>/', delete_meal, name='delete_meal'),
    path('create/meal/category/', create_meal_category, name='create_meal_category'),
    
    # end of day
    path('end-of-day/', end_of_day_view, name='end_of_day_view'),
    path('save-end-of-day/', end_of_day_view, name='save_end_of_day'),
    path('confirm_end_of_day/', confirm_end_of_day, name='confirm_end_of_day'),
    path('end_of_day_detail/<int:e_o_d_id>/', end_of_day_detail, name='end_of_day_detail'),
    path('end_of_day_list/', end_of_day_list, name='end_of_day_list'),
    
    # reorder_lis
    path('order_list', order_list, name='order_list'),
    
    # transfers
    path('transfers', transfers, name='transfers'),
    path('add/transfer/', transfer_to_production, name='add_transfer'),
    path('accept_transfer/<int:transfer_id>/', accept_transfer, name='accept_transfer'),
    path('production_transfers/', production_transfers, name='production_transfers'),
    path('receive_transfer_detail/<int:transfer_id>/', receive_transfers_detail, name='receive_transfer_detail'),
    
    # production sales
    path('production_sales/', production_sales, name='production_sales'),
    
    # check_list
    path('check_list/', check_check_list, name='check_check_list')
]

pos/urls.py
from django.urls import path
from . views import *

app_name = 'pos'

urlpatterns = [
    path('', pos, name='pos' ),
    path('process/sale/', process_sale, name='process_sale'),
    path('sales/list', sales_list, name='sales_list'),
    # path('download-receipt/', generate_receipt_pdf, name='download_receipt'),
    path('product_meal_json/', product_meal_json, name='product_meal_json'),
    path('meal/detail/json/<int:meal_id>/', meal_detail_json, name='meal_detail_json'),
    
    path('change_list/', change_list, name='change_list'),
    path('create_change/', create_change, name='create_change'),
    path('report/', download_change_report, name='download_cashbook_report'),
    path('collect_change/', collect_change, name='collect_change'),

    # sales
    path('sales/<int:user_id>/', void_sales, name='sales'),

    #authenticate
    path('void/authenticate/', void_authenticate, name='void_authenticate'),

    # cash up
    path('cash_up/<int:cashier_id>/', cash_up, name='cash_up')
]

restaurant/urls.py
from .views import Dashboard
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views

urlpatterns = [
    path('pos/', include('pos.urls', namespace='pos')),
    path('', Dashboard, name='dashborad'),
    path("admin/", admin.site.urls),
    path('settings/', include('settings.urls', namespace='settings')),
    path('users/', include('users.urls', namespace='users')),
    path('analytics/', include('analytics.urls')),
    path('finance/', include('finance.urls', namespace='finance')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

finance/models.py
from django.db import models
from inventory.models import Meal, Product, Dish
from django.contrib.auth import get_user_model

User = get_user_model()

class ExpenseCategory(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self) -> str:
        return self.name

class COGS(models.Model):
    date = models.DateField(auto_now_add=True)
    production = models.ForeignKey('inventory.production', on_delete=models.CASCADE, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    
class Expense(models.Model):
    category = models.ForeignKey(ExpenseCategory, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=255)
    cancel = models.BooleanField(default=False)
    status = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return f'{self.amount}'

class Sale(models.Model):
    cashier = models.ForeignKey(User, on_delete=models.CASCADE)
    total_amount= models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    tax = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    sub_total = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    date = models.DateField(auto_now_add=True)
    receipt_number = models.CharField(max_length=10, blank=True)
    staff = models.BooleanField(default=False)
    change = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    void = models.BooleanField(default=False)

    
    def __str__(self) -> str:
        return f'{self.cashier} -> ({self.total_amount})'
    
    def save(self, *args, **kwargs):
        if not self.receipt_number:
            last_receipt = Sale.objects.all().order_by('id').last()
            if last_receipt:
                last_receipt_number = int(last_receipt.receipt_number)
                new_receipt_number = '{:04d}'.format(last_receipt_number + 1)
            else:
                new_receipt_number = '0001'
            self.receipt_number = new_receipt_number
        super(Sale, self).save(*args, **kwargs)
    
class SaleItem(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    time = models.TimeField(auto_now_add=True)
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE, null=True)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    
class CashBook(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, null=True)
    expense = models.ForeignKey(Expense, on_delete=models.CASCADE, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    debit = models.BooleanField(default=False, null=True)
    credit = models.BooleanField(default=False, null=True)
    description = models.CharField(max_length=255, default='')
    date = models.DateField(auto_now_add=True)
    manager = models.BooleanField(default=False)
    accountant = models.BooleanField(default=False, null=True)
    director = models.BooleanField(default=False, null=True)
    note = models.TextField(default='', null=True)
    cancelled = models.BooleanField(default=False, null=True)
    
    def __str__(self) -> str:
        return f'{self.amount}'
    
class CashBookNote(models.Model):
    entry = models.ForeignKey(CashBook, related_name="notes", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    note = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Note by {self.user.username} on {self.timestamp}"
    
class transactionLog(models.Model):
    action_choice = [
        ('sale', 'sale'),
        ('expense', 'expense'),
        
    ]
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, null=True)
    expense = models.ForeignKey(Expense, on_delete=models.CASCADE, null=True)
    action = models.CharField(max_length=10, choices=action_choice)
    
    
class CashUp(models.Model):
    cashier = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cashier')
    cashed_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    sales = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return f'{self.date}'
    
class CashierAccount(models.Model):
    cashier = models.ForeignKey(User, on_delete=models.CASCADE)
    cash_up = models.ForeignKey(CashUp, on_delete=models.CASCADE, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    status = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return f'{self.cashier.first_name} ({self.amount})'

class CashierPayments(models.Model):
    date = models.DateTimeField(auto_now_add=True, null=True)
    cashier = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    
    def __str__(self) -> str:
        return f'{self.cashier.cashier.first_name} ({self.amount})'
     
class EmailNotifications(models.Model):
    expense_notification = models.BooleanField(default=True)
    
class Change(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, related_name='sale_change')
    name = models.CharField(max_length=100)
    phonenumber = models.CharField(max_length=20)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
    receipt_number = models.CharField(max_length=100)
    collected = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    cashier = models.ForeignKey(User, on_delete=models.CASCADE)
    claimed = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return f'{self.cashier.username} ({self.amount})'
    
class CashierExpense(models.Model):
    name = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    cashier = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    description = models.CharField(max_length=255)
    status = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.name} ({self.amount})'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

class CustomUserManager(BaseUserManager):
    """
    Custom user model manager with extra functionalities.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email, password and extra fields.
        If the first user created, grant them superuser and (optionally) admin group access.
        """
        if not email:
            raise ValueError('The Email field is required')
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.is_staff = True
        user.save(using=self._db)

        if self.model.objects.count() == 1:
            user.is_superuser = True
            user.company = Company.objects.get(id=1)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Creates and saves a SuperUser with the given email, password and extra fields.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is False:
            raise ValueError('Superuser must have is_staff=True.')

        if extra_fields.get('is_superuser') is False:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class Company(models.Model):
    name = models.CharField(max_length=255)
    address = models.TextField()
    

    def __str__(self) -> str:
        return self.name

class User(AbstractUser):
    
    USER_ROLES = (
        ('admin', 'Admin'),
        ('chef', 'Chef'),
        ('sales', 'Salesperson'),
        ('accountant', 'Accountant'),
        ('owner', 'Owner')
    )
    
    phonenumber = models.CharField(max_length=13)
    role = models.CharField(choices=USER_ROLES, max_length=50)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="users", null=True)
    # sessio_key = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.username

templates/inventory/production_plans.html
{% extends "base.html" %}
{% load static%}
{% load crispy_forms_tags %}
{% block title%} Production Plan {% endblock%}
{% block content %}
<style>
    @media (min-width:600px ) and (max-width:1024px){
        .checklist{
            display: none;
        }
        .col-10{
            width: 100%; 
            flex: 0 0 100%;
            max-width: 100%; 
        }
        .Production{
            margin-right: 15px;
        }
    }
    @media (max-width: 1024px) {
        .Production .production-buttons {
            display: none; 
        }
        .hamburger-menu {
            display: block;
        }
    }

    @media (min-width: 1025px) {
        .hamburger-menu {
            display: none; /
        }
    }
</style>
   <div class="Production" style="margin-left: 15px;">
        <div class="inventory-navbar">
            <nav class="d-flex justify-content-between align-items-center mt-2 mb-2">
                <div class='fw-bold d-flex align-items-center'>
                    {% if request.user.role != 'chef'%}
                        <a href='/' class='bx bx-home btn border fs-5'></a>
                    {% endif %}
                    <span class='fs-5 mx-2'>Production</span>
                </div>
                <div class="d-flex align-items-center mt-2">
                    <button class="btn btn-dark hamburger-menu" type="button" data-bs-toggle="collapse" data-bs-target="#hamburgerMenuContent" aria-expanded="false" aria-controls="hamburgerMenuContent">
                        <i class="bx bx-menu"></i>
                    </button>
    
                    <!-- Hamburger menu content -->
                    <div class="collapse" id="hamburgerMenuContent">
                        <ul class="list-unstyled mt-2">
                            <li>
                                <a href="{% url 'inventory:create_production_plan' %}" class='btn btn-outline-dark w-100 mb-2'>Create Production Plan</a>
                            </li>
                            <li>
                                <a href="{% url 'inventory:production_transfers' %}" class='btn btn-outline-dark w-100 mb-2'>Receive Transfers <span class='badge text-dark'>{{ transfer_count }}</span></a>
                            </li>
                            <li>
                                <a href="{% url 'inventory:production_raw_materials' %}" class='btn btn-outline-dark w-100 mb-2'>Production Raw Materials</a>
                            </li>
                            <li>
                                <button type="button" class='btn btn-outline-dark w-100' data-bs-toggle="modal" data-bs-target="#checklistModal">Checklist</button>
                            </li>
                        </ul>
                    </div>
                    <div class="dropdown mx-2" style="margin-top: -9px;">
                        <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                          Add
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li class="mx-2 py-2">
                                <a href="{% url 'inventory:meal_list' %}">Meals</a>
                            </li>
                            <li class="mx-2 py-2">
                                <a href="{% url 'inventory:dish_list' %}">Dishes</a>
                            </li>
                        </ul>
                    </div>
                    <ul class="list-unstyled mt-2 d-flex">
                        <li class="">
                            <a href="{% url 'inventory:create_production_plan' %}" class='btn btn-outline-dark'>Create Production Plan</a>
                        </li>
                        <li class="">
                            <a href="{% url 'inventory:production_transfers' %}" class='btn btn-outline-dark mx-2'>
                                Receive Transfers
                                <span class='badge text-dark'>{{ transfer_count }}</span>
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'inventory:production_raw_materials' %}" class='btn btn-outline-dark'>Production Raw Materials</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div>
            <div class=" mt-2 w-100">
                <table class='table border table-bordered table-hover rounded p-2' id='production_table' style="width: 100%;" >
                        <thead class='bg-primary'>
                            <tr>
                                <th>Date</th>
                                <th>PP Number</th>
                                <th>
                                    <span class='text-danger'>BY ADMIN</span>
                                    <span class='mx-2'>(Confimation Status)</span>
                                </th>
                                {% if request.user.role != 'chef'%}
                                    <th>
                                        <span class='text-danger'>BY CHEF</span>
                                        <span class='mx-2'>(Confimation Status)</span>
                                    </th>
                                {% endif %}
                                <th>Actions</th>
                            </tr>
                            </thead>
                        <tbody>
                            {% for plan in plans %}
                                <tr>
                                    <td><small>{{ plan.date_created }} {{ plan.time_created }}</small></td>
                                    <td><small>{{ plan.production_plan_number }}</small></td>
                                    <td>
                                        {% if request.user.role != 'admin' or request.user.role != 'accountant' %}
                                            <small >
                                                {% if plan.status %}
                                                    <small class="bg-success text-light p-2 rounded text-center w-100">Confirmed</small>
                                                {%else %}
                                                    <a href="{% url 'inventory:confirm_production_plan' plan.id %}" class="bg-danger text-light p-2 rounded text-center w-100">Please Confirm</a>
                                                {% endif %}
                                            </small>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if request.user.role != 'chef'%}
                                            <small>
                                                {% if plan.declared %}
                                                    <small class="bg-success text-light p-2 rounded text-center w-100" disabled>Declared</small>
                                                {% else %}
                                                    {% if plan.status %}
                                                        <a href="{% url 'inventory:declare_production_plan' plan.id %}" class="bg-danger text-light p-2 rounded text-center w-100">Waiting declaration</a>
                                                    {% else %}
                                                        <small class="bg-danger text-light p-2 rounded text-center w-100" disabled>Awaiting production plan confirmation</small>
                                                    {% endif %}
                                                {% endif %}
                                            </small>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <small>
                                            <a href="{% url 'inventory:production_plan_detail' plan.id %}" class="bx bx-show mx-2"></a>
                                            <a href="" class="bx bx-printer"></a>
                                        </small>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                </table>
            </div>
        </div>
        <div class="modal fade" id="statusFormModal" tabindex="-1" aria-labelledby="loaderModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body">
                        <h5 class="fw-bold">Change Status</h5>
                        <form action="">
                            {% csrf_token %}
                            {{ status_form | crispy }}
                            <div class="d-flex justify-content-end">
                                <div class="">
                                    <button type="reset" class="btn btn-danger btn-sm w-100">
                                        <i class='bx bx-reset'></i>
                                        Reset
                                    </button>
                                </div>
                                <span class="px-1"></span>
                                <div class="">
                                    <button type="button" onclick="changeStatus()" class="btn btn-secondary btn-sm w-100">
                                        <i class='bx bx-save'></i>
                                        change
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="loaderModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body text-center">
                        <h5 class="fw-bold">Status Successfully Changed and Related Accounts updated</h5>
                    </div>
                </div>
            </div>
        </div>
   </div> 
   <script>
        new DataTable('#production_table',{
            pageLength: 100  
        });
   </script>
{% endblock content %}

templates/inventory/receive_transfer_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Transfers{% endblock title %}
{% block content %}
<div class="products">
    <nav class='d-flex align-items-center justify-content-between border-bottom'>
        <div>
            <ul class="list-unstyled d-flex align-items-center">
                <li><a href='{% url "inventory:products"%}' class='border btn bx bx-arrow-back fs-5'></a></li>
                <li><a href='/' class='bx bx-home btn border fs-5 mx-2'></a></li>
                <li class='fs-5'>Transfer: {{ transfer.transfer_number }} </li>
            </ul>
        </div>
    </nav>
    <div class="tables">
        <table class="table table-hover table-responsive raw" id="transfers_table" style="width: 100%;">
            <thead class="bg-primary">
                <th>Date</th>
                <th>Transfer number</th>
                <th>Product</th>
                <th>Quantity</th>
            </thead>
            <tbody>
                {% for item in transfer_items  %}
                    <tr>
                        <td>
                            <small>
                                <small>{{ item.transfer.created_at }}</small>
                            </small>
                        </td>
                        <td>
                            <small>
                                <small>{{ item.transfer.transfer_number }}</small>
                            </small>
                        </td>
                        <td>
                            <small>
                                <small>{{ item.product.name }}</small>
                            </small>
                        </td>
                        <td>
                            <small>
                                <small>{{ item.quantity }}</small>
                            </small>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class='d-flex justify-content-end mt-2'>
        <a href='{% url "inventory:accept_transfer" transfer.id %}' class='btn btn-sm btn-primary text-light'>Accept</a>
    </div>
</div>
<script>
    new DataTable('#transfers_table')
</script>
{% endblock content %}